cheveningdbtrial1/cheveningdbtrial1/urls.py
from django.contrib import admin
from django.urls import path, include
from dbusers import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('dbusers.urls')),
    path('register/', views.register, name='register'),
]

cheveningdbtrial1/dbusers/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views 

app_name = 'dbusers'


urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='dbusers/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='dbusers/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
]

cheveningdbtrial1/dbusers/models.py
from django.db import models

# Create your models here.

cheveningdbtrial1/dbusers/forms.py
from django.contrib.auth.forms import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

cheveningdbtrial1/dbusers/views.py
from django.shortcuts import render
# from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import UserRegisterForm
def home(request):
    return render(request, 'dbusers/home.html')

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Hi {username} your account was created successfully')
            return redirect('home')
            # return redirect(request, 'dbusers/register_success.html')
        #  else:
        #     return render(request, 'dbusers/register_failure.html')
    else:
        form = UserRegisterForm() 
    return render(request, 'dbusers/register.html', {'form': form})

def login(request):
    return render(request, 'dbusers/login.html')

def logout(request):
     return render(request, 'dbusers/logout.html')   

def profile(request):
    return render(request, 'dbusers/profile.html')

# def reset_password(request):
#     return render(request, 'dbusers/reset_password.html')

# def change_password(request):
#     return render(request, 'dbusers/change_password.html')

# def delete_account(request):
#     return render(request, 'dbusers/delete_account.html')   

# def update_profile(request):
#     return render(request, 'dbusers/update_profile.html')

# def update_profile_picture(request):
#     return render(request, 'dbusers/update_profile_picture.html')

# def register_success(request):
#     return render(request, 'dbusers/register_success.html')

# def login_success(request):
#     return render(request, 'dbusers/login_success.html')

# def logout_success(request):
#     return render(request, 'dbusers/logout_success.html')

# def register_failure(request):
#     return render(request, 'dbusers/register_failure.html')

# def login_failure(request):
#     return render(request, 'dbusers/login_failure.html')

# def logout_failure(request):
#     return render(request, 'dbusers/logout_failure.html')

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        messages.success(request, 'You have been logged out successfully.')
        return redirect('dbusers:home')  # Adjust this according to your URL configuration
    return redirect('dbusers:home')  # Redirect if accessed via GET

cheveningdbtrial1/dbusers/templates/dbusers/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Css Style -->
    <link rel="stylesheet" href="{% static 'dbusers/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- Font Link -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Open+Sans:wght@800&display=swap" rel="stylesheet">
  </head>

  <body id="bg" style="background-image: url({% static 'dbusers/images/bg.png' %});">
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="main-navbar">
      <div class="container">
        <a class="navbar-brand" href="{% url 'dbusers:home' %}">
          <img src="{% static 'dbusers/images/in-logo-1.svg' %}" alt="Logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
            <a class="nav-link" href="#">Market</a>
            <a class="nav-link" href="#">Company</a>
            <a class="nav-link" href="#">Education</a>
            <a class="nav-link" href="#">Resources</a>
          </div>
          <div class="d-flex" id="authstyle">
            {% if user.is_authenticated %}
              <a href="{% url 'dbusers:profile' %}" class="btn" style="color: white; background-color: #0f64bf;" id="header-links"> Profile </a>
              <form id = "logout-form" action="{% url 'dbusers:logout' %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn" style="color: white; background-color: #0f64bf;" id="header-links"> Log Out </button>
              </form>
            {% else %}
              <a href="{% url 'dbusers:register' %}" class="btn" style="color: white; background-color: #0f64bf;" id="header-links"> Create Account </a>
              <a href="{% url 'dbusers:login' %}" class="btn" style="color: white; background-color: #0f64bf; margin-left: 10px;" id="header-links"> Log In </a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
 
    <div>
      <div class="container">
        {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor%}
        {% endif %}
      </div>
      {% block content %}
      {% endblock content %}
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>

cheveningdbtrial1/dbusers/templates/dbusers/home.html
{% extends 'dbusers/base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container">
            <div class="row g-0">
                <div class="col-sm-6 col-md-8" id="header-text">
                    <h1 id="header-h1"> Chevening Alumni <br> Ranked 12th in the UK </h1>
                    <p id="header-paragraph">Scholarship at Aberdeen, <br> Offering outstand student satisfaction</p>
                    <a class="btn" style="color: white; background: linear-gradient(to right, rgb38, 38, 228, rgb(219, 192, 41)); "type="submit" id="body-link-row">Discover More</a>
                </div>

            <div class="col-6 col-md-4" id="header-image"><img src="images/in-liquid-slide-2.svg " alt=""></div>
            </div>
    </div>
   

{% endblock %}

cheveningdbtrial1/dbusers/templates/dbusers/login.html
{% extends 'dbusers/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container" style="margin-top: 30px;">
    <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4" style="color: white;">Sign In Now</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group" id="signup-button">
          <button class="btn ">Sign In</button>
      </div>
      <div class="form-group">
          <small class="text-muted ml-3" >Don't have an account yet? <a href="{% url 'dbusers:register' %}">Sign Up</a></small>
      </div>
    </form>
    </div>

{% endblock %}

cheveningdbtrial1/dbusers/templates/dbusers/logout.html
{% extends 'dbusers/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        <h1>You have been Logged out</h1>
        <h5><a href="{% url 'dbusers:login' %}">Login In Again</a></h5>
    </div>
{% endblock %} 

cheveningdbtrial1/dbusers/templates/dbusers/profile.html
{% extends 'dbusers/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class = "container">
        <h2>{{user.username}}</h2>
        <h2>{{user.email}}</h2>   
    </div>
{% endblock %}

cheveningdbtrial1/dbusers/templates/dbusers/register.html
{% extends 'dbusers/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container" style="margin-top: 30px;">
    <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4" style="color: white;">Join Now</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group" id="signup-button">
          <button class="btn ">Sign Up</button>
      </div>
      <div class="form-group">
          <small class="text-muted ml-3" >Already have an account? <a href="{% url 'dbusers:login' %}">Sign In</a></small>
      </div>
    </form>
    </div>

{% endblock %}